language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

go:
  - 1.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

stages:
  - lint
  - test

script: make test

after_success: if [ -f coverage.out ]; then bash <(curl -s https://codecov.io/bash); fi

jobs:
  include:
    - stage: lint
      script: make lint
      after_success: curl -d "repo=github.com/${TRAVIS_REPO_SLUG}" https://goreportcard.com/checks
